export const colors = {
  orange: () => "var(--orange)",
  white: () => "var(--white)",
  gray: () => "var(--gray)",
  sky: () => "var(--sky)",
  cyan: () => "var(--cyan)",
  teal: () => "var(--teal)",
  yellow: () => "var(--yellow)",
  avocado: () => "var(--avocado)",
  amber: () => "var(--amber)",
  green: () => "var(--green)",
  emerald: () => "var(--emerald)",
  lime: () => "var(--lime)",
  rose: () => "var(--rose)",
  pink: () => "var(--pink)",
  fuchsia: () => "var(--fuchsia)",
  purple: () => "var(--purple)",
  violet: () => "var(--violet)",
  indigo: () => "var(--indigo)",
  blue: () => "var(--blue)",
  red: () => "var(--red)",
};

export const txColors = /** @type {const} */ ({
  v1: colors.blue(),
  v2: colors.violet(),
  v3: colors.fuchsia(),
  rbf: colors.orange(),
  noRbf: colors.gray(),
  oneInput: colors.yellow(),
  multiInput: colors.amber(),
  oneOutput: colors.emerald(),
  multiOutput: colors.green(),
  p2pk: colors.yellow(),
  p2pkh: colors.amber(),
  p2sh: colors.orange(),
  p2wpkh: colors.emerald(),
  p2wsh: colors.green(),
  taproot: colors.violet(),
  p2a: colors.cyan(),
  baremult: colors.fuchsia(),
  opReturn: colors.red(),
  empty: colors.gray(),
  unknown: colors.gray(),
});
